### ISSUE TITLE
Maximum Number of Subplots Reached

### ISSUE THREAD

**Issue by piccolomo** [piccolomo/plotext#150]
For clarity, I transfer here this issue, initially posted in [Issue 144](https://github.com/piccolomo/plotext/issues/144), by @ineteye.  

---

Hi!

I tried your code with bigger list but always getting error: 'list index out of range' on plt.show()
Think its cause screen height

```

import plotext as plt
plt.clf()
plt.clc()
plt.subplots(1,2)
 
plt.subplot(1,1).plot([1,2])
plt.xfrequency(0)
plt.yfrequency(0)
 
plt.subplot(1,2).plot_size(10,None)

symbol = 'OMI'
symbols=['IONS','CDNA','*ARCT','*ARCT','*DVAX','ABBV','OSTK','PYPL','GMKN','AXSM','IRT','*ANF','CDNA','LCID','*VTNR','*RPD','NFLX','TOST','LOVE','CC','NVDA','PYPL','TWTR','*RCII','FRPT','BGS','VIRT','AMAT','RIFUSDT']

S = len(symbols)
plt.subplots(S, 1)
for s in range(S):
    bg = 'orange+' if symbols[s] == symbol else None
    plt.subplot(1,2).subplot(s + 1, 1).text(symbols[s], 0, 0, alignment="left", background = bg, color = 'white')
    plt.subplot(1,2).subplot(s + 1, 1).plotsize(None, 1) if s != S - 1 else None

plt.subplot(1,2) 
plt.frame(0)
plt.xfrequency(0)
plt.yfrequency(0)
plt.xlim(0, 1)
plt.ylim(-1, 0)

plt.show()
```

_Originally posted by @ineteye in https://github.com/piccolomo/plotext/issues/144#issuecomment-1282871961_

**Comment by piccolomo** [comment]
Hi @ineteye,

issue solved in new GitHub version. To install: `pip install git+https://github.com/piccolomo/plotext`. Could you kindly double check?

I hope it helps and thanks for the report, it was very helpful to bust of couple of issue (the other one was posted in [issue 151](https://github.com/piccolomo/plotext/issues/151)).

**Comment by ineteye** [comment]
Hi!
1. Install update: pip install git+https://github.com/piccolomo/plotext
2. Check today second time... but still getting error: "list index out of range"
i have 29 symbols and 42 height,testing in Vscode:
symbols: 29  plt.th: 42
3. In Terminal similar error:
![image](https://user-images.githubusercontent.com/32996306/198600327-dea7e912-62a3-435b-9c19-db1a2ac91f7f.png)

**Comment by piccolomo** [comment]
Hi @ineteye, I have doubled checked as well and all goes well on my side. 

The only thing I can think is that your version is still an old one due perhaps to some ghost `plotext` versions remaining in your system. 
Check the version with `plt.version` which should be 5.2.8. If it is lower, try to locate old `plotext` versions and remove them manually, then reinstall from `git`. 

Thanks again of reporting, please keep updated.
Savino

**Comment by ineteye** [comment]
Yes. have to
`pip uninstall plotext`
and then 
`pip install git+https://github.com/piccolomo/plotext`
and finally it works ;)
![image](https://user-images.githubusercontent.com/32996306/198691769-ca2eed18-2657-493f-b580-ae86a0bb89b4.png)

**Comment by piccolomo** [comment]
Ye! I'm glad it works!
